"""added image to collection model

Revision ID: 558110345a4b
Revises: e65a79714603
Create Date: 2023-08-29 09:52:43.648935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558110345a4b'
down_revision = 'e65a79714603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
